# DEFAULT MAIN PAGE REQUEST
GET http://localhost:3000/

###


GET http://localhost:3000/user

###


GET http://localhost:3000/user?s=1

###


GET http://localhost:3000/user/2/

###



GET http://localhost:3000/user

###



// POST - send user to DB
POST http://localhost:3000/user
Content-Type: application/x-www-form-urlencoded

name=Fred&age=32
###


GET http://localhost:3000/user/new

###
