# DEFAULT MAIN PAGE REQUEST
GET http://localhost:3000/

###



GET http://localhost:3000/user/1

###



GET http://localhost:3000/user

###



// POST - send user to DB
POST http://localhost:3000/user
Content-Type: application/x-www-form-urlencoded

name=Martin&age=36
###

